;;; KeyBorads
(defun svdesk()
  (interactive)
  (desktop-save "~/.emacs.d/desktop/"))
(defun opdesk()
  (interactive)
  (make-directory "~/.emacs.d/desktop/" t)
  (desktop-read "~/.emacs.d/desktop/"))
(defun kb (keyString command)
  "short write of global set key,argv:KEYSTRING COMMAND."
  (global-set-key (kbd keyString) command))
(defun open-user-custom-file ()
  (interactive)
  (find-file "~/.emacs.d/user-custom/user-custom.el"))
(define-prefix-command 'meta-d-map)
(kb "<f6>" 'dashboard-mode)
(kb "RET" 'newline-and-indent)
(kb "M-d" nil)
(kb "M-d b d" 'kill-this-buffer)
(kb "M-d b w d" 'kill-buffer-and-window)
(kb "M-d c a" 'format-all-buffer)
(kb "M-d c c" 'comment-or-uncomment-region)
(kb "M-d c s" 'sort-lines)
(kb "M-d d o" 'opdesk)
(kb "M-d d s" 'svdesk)
(kb "M-d f l" 'goto-line-preview)
(kb "M-d f d o" 'open-user-custom-file)
(kb "M-d o e" 'doing-org-short-example)
(kb "M-d o q" 'doing-org-short-quote)
(kb "M-d o s" 'doing-org-short-src)
(kb "M-d w -" 'split-window-below)
(kb "M-d w /" 'split-window-right)
(kb "M-d w c +" 'enlarge-window)
(kb "M-d w c -" 'shrink-window)
(kb "M-d w d" 'delete-window)
(kb "M-d w h  +" 'enlarge-window-horizontally)
(kb "M-d w h -" 'shrink-window-horizontally)
(provide 'keys)
;;; keys.el ends here
