(require 'package)
(package-initialize)
(add-to-list 'package-archives
             '("melpa" . "http://melpa.org/packages/"))
;;; Packages
(setq user-package-directory "~/.emacs.d/")
(add-to-list 'load-path "~/.emacs.d/site-lisp/dash.el/")
(add-to-list 'load-path "~/.emacs.d/site-lisp/ht.el/")
(add-to-list 'load-path "~/.emacs.d/site-lisp/hydra/")
(add-to-list 'load-path "~/.emacs.d/site-lisp/pfuture/")
(add-to-list 'load-path "~/.emacs.d/site-lisp/singles/")
(require 'add-path)
(require 'smalls)
(require 'config-window-numbering)
(require 'config-ivy)
(require 'config-dashboard)
(require 'config-org-mode)
(require 'config-treemacs)
(require 'config-auto-save)
(require 'config-sort-tab)
(require 'config-treesit)
(if doingemacs-enable-language-complete (progn (require 'config-company)
					       (require 'config-lsp)))
(require 'doing-translate)
(if doingemacs-enable-eaf (require 'config-eaf))
(provide 'plugin)
;;; plugin.el ends here
